version: '3.8'

services:
  caldo-ui:
    image: noserdocker/caldo-ui:latest
    ports:
      - 8008:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  caldo-api:
    image: noserdocker/caldo-api:latest
    environment:
      BASE_URL: ${BASE_URL}
    volumes:
      - ./data:/app/Data
    ports:
      - 80
