services:
  caldo-ui:
    image: noserdocker/caldo-ui:latest
    container_name: caldo-ui
    restart: unless-stopped
    environment:
      COMPOSE_PROJECT_NAME: "caldo"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - core

  caldo-api:
    image: noserdocker/caldo-api:latest
    container_name: caldo-api
    restart: unless-stopped
    environment:
      BASE_URL: ${BASE_URL}
      COMPOSE_PROJECT_NAME: "caldo"
    volumes:
      - ./data:/app/Data
    ports:
      - 80
    networks:
      - core

networks:
  core:
    external: true
