version: '3.8'

services:
  caldo-ui:
    image: caldo-ui:dev
    container_name: caldo-ui
    build:
      context: ../src/Client/
      dockerfile: Dockerfile
    ports:
      - 8008:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  caldo-api:
    image: caldo-api:dev
    container_name: caldo-api
    environment:
      BASE_URL: http://localhost:8008
    build:
      context: ..
      dockerfile: src/Dockerfile
    volumes:
      - ./data:/app/Data
