version: "3.8"

services:
  caldo-ui-test:
    image: noserdocker/caldo-ui:develop
    container_name: caldo-ui-test
    security_opt:
      - label:com.centurylinklabs.watchtower.scope:watched
    ports:
      - 8009:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      COMPOSE_PROJECT_NAME: "caldo-test"

  caldo-api-test:
    image: noserdocker/caldo-api:develop
    container_name: caldo-api-test
    security_opt:
      - label:com.centurylinklabs.watchtower.scope:watched
    environment:
      BASE_URL: ${BASE_URL_TEST}
      COMPOSE_PROJECT_NAME: "caldo-test"
    volumes:
      - ./data:/app/Data
    ports:
      - 80
