version: '3.8'

services:
  caldo-ui:
    image: noserdocker/caldo-ui:develop
    container_name: caldo-ui-test
    ports:
      - 8009:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  caldo-api:
    image: noserdocker/caldo-api:develop
    container_name: caldo-api-test
    environment:
      BASE_URL: ${BASE_URL_TEST}
    volumes:
      - ./data:/app/Data
    ports:
      - 80
